### ISSUE TITLE
Openlane at rcx_mcsta.min stage crasses with segmentation fault

### ISSUE THREAD

**Issue by dineshannayya** [The-OpenROAD-Project/OpenLane#1482] opened 2022-11-11 07:13 UTC
### Description

With latest openlane at rcx_mcsta.min stage  fails with segmentation fault.

<pre>[INFO]: Checking Wire Lengths (log: wb_host/runs/wb_host/logs/routing/20-wire_lengths.log)...
[STEP 21]
[INFO]: Running SPEF Extraction at the min process corner (log: wb_host/runs/wb_host/logs/signoff/21-parasitics_extraction.min.log)...
[STEP 22]
[INFO]: Running Multi-Corner Static Timing Analysis at the min process corner (log: wb_host/runs/wb_host/logs/signoff/22-rcx_mcsta.min.log)...
[ERROR]: during executing openroad script /openlane/scripts/openroad/sta_multi_corner.tcl
[ERROR]: Log: wb_host/runs/wb_host/logs/signoff/22-rcx_mcsta.min.log
[ERROR]: Last 10 lines:
39# 0x00007F58169B4F1E in /lib64/libtcl8.5.so
40# Tcl_EvalEx in /lib64/libtcl8.5.so
41# Tcl_Eval in /lib64/libtcl8.5.so
42# sta::sourceTclFile(char const*, bool, bool, Tcl_Interp*) in openroad
43# ord::tclAppInit(Tcl_Interp*) in openroad
44# Tcl_Main in /lib64/libtcl8.5.so
45# main in openroad
46# __libc_start_main in /lib64/libc.so.6
47# 0x0000000000CA05E7 in openroad
child killed: segmentation violation

[ERROR]: Creating issue reproducible...
[INFO]: Saving runtime environment...
OpenLane TCL Issue Packager
</pre>

### Expected Behavior

Expected clean openlane flow.

### Environment report

```shell
<pre><font color="#4E9A06"><b>dinesha@lenovo-i3-10100-07IMB05</b></font>:<font color="#3465A4"><b>~/workarea/efabless/MPW-7/OpenLane</b></font>$ python3 ./env.py issue-survey
Kernel: Linux v5.15.0-50-generic
Distribution: ubuntu 20.04
Python: v3.8.10 (OK)
Container Engine: docker v20.10.17 (OK)
OpenLane Git Version: a0b19fa68b79eff3e29b674106b06d20aab637f1
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

a0b19fa 2022-11-01T19:09:25+02:00 Add Wire Length Checker (#1463) - Mohamed Gaber -  (HEAD -&gt; master)
1f923eb 2022-11-01T12:07:33+02:00 [BOT] Update openroad_app (#1435) - Openlane Bot -  ()
41ed003 2022-10-25T20:04:52+02:00 Fix get_design_path (#1450) - Liu Yihua -  ()
---
Git Remotes

origin	https://github.com/efabless/OpenLane.git (fetch)
origin	https://github.com/efabless/OpenLane.git (push)
</pre>
```

### Reproduction material

[issue_reproducible.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/9987313/issue_reproducible.tar.gz)
[22-rcx_mcsta.min.log.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/9987560/22-rcx_mcsta.min.log.gz)

### Relevant log output

```shell
<pre>[ERROR]: during executing openroad script /openlane/scripts/openroad/sta_multi_corner.tcl
[ERROR]: Log: wb_host/runs/wb_host/logs/signoff/22-rcx_mcsta.min.log
[ERROR]: Last 10 lines:
39# 0x00007F58169B4F1E in /lib64/libtcl8.5.so
40# Tcl_EvalEx in /lib64/libtcl8.5.so
41# Tcl_Eval in /lib64/libtcl8.5.so
42# sta::sourceTclFile(char const*, bool, bool, Tcl_Interp*) in openroad
43# ord::tclAppInit(Tcl_Interp*) in openroad
44# Tcl_Main in /lib64/libtcl8.5.so
45# main in openroad
46# __libc_start_main in /lib64/libc.so.6
47# 0x0000000000CA05E7 in openroad
child killed: segmentation violation

[ERROR]: Creating issue reproducible...
[INFO]: Saving runtime environment...
OpenLane TCL Issue Packager

EFABLESS CORPORATION AND ALL AUTHORS OF THE OPENLANE PROJECT SHALL NOT BE HELD
LIABLE FOR ANY LEAKS THAT MAY OCCUR TO ANY PROPRIETARY DATA AS A RESULT OF USING
THIS SCRIPT. THIS SCRIPT IS PROVIDED ON AN &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND.

BY USING THIS SCRIPT, YOU ACKNOWLEDGE THAT YOU FULLY UNDERSTAND THIS DISCLAIMER
AND ALL IT ENTAILS.

Parsing config file(s)…
Setting up /home/dinesha/workarea/opencore/git/riscduino/openlane/wb_host/runs/wb_host/issue_reproducible…
Done.
[INFO]: Reproducible packaged: Please tarball and upload &apos;wb_host/runs/wb_host/issue_reproducible&apos; if you&apos;re going to submit an issue.
[INFO]: Saving current set of views in &apos;wb_host/runs/wb_host/results/final&apos;...
[INFO]: Generating final set of reports...
[INFO]: Created manufacturability report at &apos;wb_host/runs/wb_host/reports/manufacturability.rpt&apos;.
[INFO]: Created metrics report at &apos;wb_host/runs/wb_host/reports/metrics.csv&apos;.
[INFO]: Saving runtime environment...
[ERROR]: Flow failed.
</pre>
```

**Comment by vijayank88** [comment] 2022-11-11 07:22
@dineshannayya 
Duplicate of #1467.
Its got resolved it with this PR: https://github.com/The-OpenROAD-Project/OpenLane/pull/1466
Please update commit to latest to resolve above issue.

**Closed by vijayank88** 2022-11-11 07:22 UTC
