### ISSUE TITLE
Global Placement error: RePlAce diverged at newStepLength

### ISSUE THREAD

**Issue by nguyendao-uom** [The-OpenROAD-Project/OpenLane#657] opened 2021-10-20 16:17 UTC
### Description
I got the [ERROR GPL-0305] RePlAce diverged at newStepLength during Global Placement. I've tried all of the following options but still got the error:
The DIE_AREA is set much larger than the core area (macros + std_cells) 
Tested with the `set env::(PL_TARGET_DENSITY)` = 0.3, 0.2 or 0.65 
Set Halo to 50 (FP_HORIZONTAL_HALO, FP_VERTICAL_HALO) and channel width (between macros) to 5, 10 um

### Environment
```
Operating System Information: Linux cspc083 4.18.0-338.el8.x86_64
Docker Version: 20.10.8, build 3967b7d
OpenLane Tag: 2021.10.08_02.00.18

```

### Reproduction Material
make mount
./flow.tcl -design eFPGA_top

### Logs
```
...
Placing Inst_eFPGA.Tile_X9Y8_RAM_IO
Placing Inst_eFPGA.Tile_X9Y9_RAM_IO
Successfully placed 138 instances
...
[INFO GPL-0002] DBU: 1000
[INFO GPL-0003] SiteSize: 460 2720
[INFO GPL-0004] CoreAreaLxLy: 5520 10880
[INFO GPL-0005] CoreAreaUxUy: 3194240 3587680
[INFO GPL-0006] NumInstances: 70898
[INFO GPL-0007] NumPlaceInstances: 2822
[INFO GPL-0008] NumFixedInstances: 55740
[INFO GPL-0009] NumDummyInstances: 12336
[INFO GPL-0010] NumNets: 31696
[INFO GPL-0011] NumPins: 67045
[INFO GPL-0012] DieAreaLxLy: 0 0
[INFO GPL-0013] DieAreaUxUy: 3200000 3600000
[INFO GPL-0014] CoreAreaLxLy: 5520 10880
[INFO GPL-0015] CoreAreaUxUy: 3194240 3587680
[INFO GPL-0016] CoreArea: 11405413696000
[INFO GPL-0017] NonPlaceInstsArea: 7901419051300
[INFO GPL-0018] PlaceInstsArea: 30691936000
[INFO GPL-0019] Util(%): 0.88
[INFO GPL-0020] StdInstsArea: 30691936000
[INFO GPL-0021] MacroInstsArea: 0
[InitialPlace]  Iter: 1 CG Error: 0.00208041 HPWL: 21196105310
[InitialPlace]  Iter: 2 CG Error: 0.00091308 HPWL: 21162674343
[InitialPlace]  Iter: 3 CG Error: 0.00037039 HPWL: 20843645888
[InitialPlace]  Iter: 4 CG Error: 0.00008030 HPWL: 20558601835
[InitialPlace]  Iter: 5 CG Error: 0.00004696 HPWL: 20420597739
[InitialPlace]  Iter: 6 CG Error: 0.00004526 HPWL: 20388830846
[InitialPlace]  Iter: 7 CG Error: 0.00003559 HPWL: 20378814865
[InitialPlace]  Iter: 8 CG Error: 0.00003044 HPWL: 20372391763
[InitialPlace]  Iter: 9 CG Error: 0.00005220 HPWL: 20368463074
[InitialPlace]  Iter: 10 CG Error: 0.00002006 HPWL: 20367796117
[InitialPlace]  Iter: 11 CG Error: 0.00002991 HPWL: 20367532875
[InitialPlace]  Iter: 12 CG Error: 0.00002805 HPWL: 20366412805
[InitialPlace]  Iter: 13 CG Error: 0.00001094 HPWL: 20366153170
[InitialPlace]  Iter: 14 CG Error: 0.00001320 HPWL: 20365761937
[InitialPlace]  Iter: 15 CG Error: 0.00001909 HPWL: 20365357198
[InitialPlace]  Iter: 16 CG Error: 0.00000529 HPWL: 20365030698
[INFO GPL-0031] FillerInit: NumGCells: 180237
[INFO GPL-0032] FillerInit: NumGNets: 31696
[INFO GPL-0033] FillerInit: NumGPins: 67045
[INFO GPL-0023] TargetDensity: 0.55
[INFO GPL-0024] AveragePlaceInstArea: 10875951
[INFO GPL-0025] IdealBinArea: 19774456
[INFO GPL-0026] IdealBinCnt: 576775
[INFO GPL-0027] TotalBinArea: 11405413696000
[INFO GPL-0028] BinCnt: 512 512
[INFO GPL-0029] BinSize: 6228 6986
[INFO GPL-0030] NumBins: 262144
[NesterovSolve] Iter: 1 overflow: 2.03612 HPWL: 1226425097
...
[NesterovSolve] Iter: 2210 overflow: 1.14712 HPWL: 1900589116
[NesterovSolve] Iter: 2220 overflow: 1.15509 HPWL: 1901636738
[ERROR GPL-0305] RePlAce diverged at newStepLength.
Error: or_replace.tcl, 94 GPL-0305
```

**Comment by maliberty** [comment] 2021-10-22 03:24
The challenge is that there is no placement sites in the channel so some instances coming from global placement are nowhere near a legal site.  Our usual strategy of just pushing instance off of any overlapping macro doesn't work as there are no nearby sites.  

I'll work on an detailed placer enhancement to find a nearest site to seed the search.  In the meantime you could make your channels wide enough to accommodate some placement sites as a further workaround.

Btw, is it ok if I convert your test case into a regression for OR?

**Comment by nguyendao-uom** [comment] 2021-11-01 15:49
@maliberty Have you got any update on "detailed placer enhancement to find a nearest site to seed the search" as mentioned? 
It's weird that some buffers were placed in the channel (see picture below), which expected to be empty with `FP_HORIZONTAL_HALO` and `FP_VERTICAL_HALO`?
Also, when I made the channel wider, it passed the placement but got routing congestion. Do you have any idea/suggestions why routing congestion is too high for those closed/aligned pins?
Thanks.
![Screen Shot 2021-11-01 at 3 28 37 pm](https://user-images.githubusercontent.com/70208346/139697833-ac7e513e-f5fa-4d15-b019-0bdfc57fcbed.png)

**Comment by maliberty** [comment] 2021-11-01 15:52
Sorry some other interrupts took priority.   I think the interesting case is with wider channels and global routing.  The global router is tuned to more general routing and likely overestimates congestion for this specialized case.  You might try -allow_overflow as a workaround.

**Comment by maliberty** [comment] 2021-11-01 15:59
The narrower channels will require enhancing the detailed placer (it assumes there will be sites in between macros in its current heuristics).  However do you have a strategy to handle the tapcell rules with these channels as no tapcells can be inserted into the channels?

**Comment by nguyendao-uom** [comment] 2021-11-01 16:14
You mean the distance between the tapcells? they are in all the macros with sufficient offsets and distances, adding a narrow channel should be fine (I expect).

**Comment by maliberty** [comment] 2021-11-01 16:41
It depends how wide the channels are and how close to the macro edge the tapcells are.

**Comment by nguyendao-uom** [comment] 2021-11-08 09:39
@maliberty can we set a Halo just for a particular block in Openlane? Btw, any chance for an Openlane update to resolve this issue (wrong placement when the channel is narrow) by this week? We actually keen to have open everything for the mpw-3 shuttle run. Thanks

**Comment by maliberty** [comment] 2021-11-08 16:55
OR allows per block halos, not sure about the OL interface to do so.

I'll give it higher priority since you are in mpw-3.  Given the short time I think it is best to stick with the bigger channels for now and focus on the routing issues.

**Comment by nguyendao-uom** [comment] 2021-11-08 17:05
Thanks @maliberty. I don't see the option for a single block halo in OL? 
Do we also have set_dont_touch constraint for the net in OL? I just want to tool do not insert buffers between macro's IOs.
In the mean time, I'll try abutting pin option and/or widening the channels

**Comment by nguyendao-uom** [comment] 2021-11-10 16:58
Hi @maliberty, Have you tried to resolve the placement issue for the narrow channel? I have tried abutting the pins and seems all the pins are well aligned. That will resolve the issue of overestimates congestion. 
But again, the wrong placement is preventing us to stitch the tiles using OL. It would be great if we can fix this issue soon.
Thanks

![fabric_wrong_placement](https://user-images.githubusercontent.com/70208346/141156414-878ca621-38ae-467a-be95-0568f6164a93.png)

Here is the updated tarball
 
[std_mux4_or_opendp_packaged.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7514507/std_mux4_or_opendp_packaged.tar.gz)

**Comment by maliberty** [comment] 2021-11-10 17:56
You can work around the detailed placement problem for now by using -max_displacement.  I found on your case 2000 removed the failures.  It will slow down placement but for this small designs it is ok.

**Comment by nguyendao-uom** [comment] 2021-11-10 18:36
Where should I add that option to? Thanks

**Comment by maliberty** [comment] 2021-11-10 18:49
The detailed_placement command.

**Comment by maliberty** [comment] 2021-11-10 21:21
FYI, the detailed placement problem is addressed in https://github.com/The-OpenROAD-Project/OpenROAD/pull/1292 (pending code review).

**Comment by donn** [comment] 2021-11-10 21:23
If it's not too much of a hassle, drop me a slack message when it's merged?

**Comment by nguyendao-uom** [comment] 2021-11-11 10:51
Thanks @maliberty. That works for the overlapping errors. That option also is needed when running cts for placing the clock buffers.
Now it's stuck at routing step caused by "out of memory". I have tried with `$export DOCKER_SWAP=-1` and`$export DOCKER_MEMORY=64gb` but does not work. 
Any suggestions to resolve it?

```
[INFO GRT-0101] Running extra iterations to remove overflow.
Error: out of memory.[INFO]: Changing layout from /openLANE_flow/designs/eFPGA_top/runs/std_mux4/results/placement/eFPGA_top.placement.def to /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/routing/17-fastroute.def
[INFO]: Changing layout from 0 to /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/routing/17-fastroute.guide
[INFO]: Changing layout from /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/routing/17-fastroute.def to /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/routing/17-fastroute.def
[INFO]: Changing layout from /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/routing/17-fastroute.guide to /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/routing/17-fastroute.guide
[INFO]: Current Def is /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/routing/17-fastroute.def
[INFO]: Current Guide is /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/routing/17-fastroute.guide
[INFO]: Running Fill Insertion...
[INFO]: current step index: 18
OpenROAD v2.0-1164-g7f23e5f 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[INFO ODB-0222] Reading LEF file: /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/merged_unpadded.lef
[WARNING ODB-0220] WARNING (LEFPARS-2036): SOURCE statement is obsolete in version 5.6 and later.
The LEF parser will ignore this statement.
To avoid this warning in the future, remove this statement from the LEF file with version 5.6 or later. See file /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/merged_unpadded.lef at line 973.

[INFO ODB-0223]     Created 13 technology layers
[INFO ODB-0224]     Created 25 technology vias
[INFO ODB-0225]     Created 456 library cells
[INFO ODB-0226] Finished LEF file:  /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/merged_unpadded.lef
[ERROR ORD-0003] /openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/routing/17-fastroute.def does not exist.
ORD-0003
```

**Comment by maliberty** [comment] 2021-11-11 14:57
"/openLANE_flow/designs/eFPGA_top/runs/std_mux4/tmp/routing/17-fastroute.def does not exist."  doesn't seem to be a out of memory issue.  What makes you say it is oom?

**Comment by maliberty** [comment] 2021-11-11 15:00
@donn merged The-OpenROAD-Project/OpenROAD#1292

**Comment by nguyendao-uom** [comment] 2021-11-11 15:08
It showed in log file above, the first error

**Comment by maliberty** [comment] 2021-11-11 16:41
@donn the flow should not continue after a step fails due to oom

@nguyendao-uom would you package this at the global_route step?

**Comment by nguyendao-uom** [comment] 2021-11-11 17:22
@maliberty Please check this
[std_mux4_or_groute_packaged.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7522157/std_mux4_or_groute_packaged.tar.gz)

**Comment by maliberty** [comment] 2021-11-12 05:18
@eder-matheus would you take a look at this newest groute issue.  I see grt stays at <1G mem through routing but the memory starts shooting up during antenna fixing.

**Comment by nguyendao-uom** [comment] 2021-11-17 11:32
@eder-matheus any updates from your end? thanks

**Comment by donn** [comment] 2021-11-17 11:58
@maliberty @nguyendao-uom We're still blocked on a number of issues when it comes to merging the latest version of OpenROAD: Primarily, https://github.com/The-OpenROAD-Project/OpenROAD/issues/1309, but I'm not shocked if more pop up later…

**Comment by nguyendao-uom** [comment] 2021-11-25 10:51
@donn any updates yet?

**Comment by donn** [comment] 2021-11-25 12:51
Yeah, it's been merged yesterday. Thank you for your patience.

**Closed by donn** 2021-11-25 12:51 UTC
Labels: bug, OpenROAD
