### ISSUE TITLE
[PDNGEN Issue] -  PDN does not honor the FP_PDN_HORIZONTAL_HALO & FP_PDN_VERTICAL_HALO value

### ISSUE THREAD

**Issue by dineshannayya** [The-OpenROAD-Project/OpenLane#1262] opened 2022-08-11 17:27 UTC
### Description

My openlane flow global routing stage fails with DRC failure, further debug shows that PDNGen does not honor the minimum spacing margin specification for Macro boundary and connecting the MET4 Power Strip near to MACRO Boundary, Due to this global routing stage fails with DRC failure.  FYI:  SRAM Macro has Pin at MET4.  

![mpw7-pdngen-issue](https://user-images.githubusercontent.com/8286294/184193414-7644aec0-f7ca-4cb5-a502-ae4224fc23e0.png)

 
### Environment
<pre>python3 ./env.py issue-survey
Kernel: Linux v5.15.0-41-generic
Distribution: ubuntu 20.04
Python: v3.8.10 (OK)
Container Engine: docker v20.10.17 (OK)
OpenLane Git Version: 6ab944bc23688cae6dc6fa32444891a1e57715c8
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

6ab944b 2022-08-09T14:51:35+02:00 IR Drop Reports in the Signoff Stage (#1255) - Mohamed Gaber -  (HEAD -&gt; master)
4476a58 2022-07-29T16:03:10+02:00 Sky130 Enhancements (#1240) - Mohamed Gaber -  ()
4f63c8c 2022-07-27T17:26:27+02:00 Various CI Fixes (#1235) - Mohamed Gaber -  ()
---
Git Remotes

origin	https://github.com/efabless/OpenLane.git (fetch)
origin	https://github.com/efabless/OpenLane.git (push)
</pre>

### Reproduction Material
[issue_reproducible.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/9310642/issue_reproducible.tar.gz)

### Expected behavior
PDNGen need to honor the minimum spacing margin specification for Macro boundary 

### Logs
There is no failure at PDN stage, but openlane flow failure at global routing phase.  I have created test-setup at after PDN stage

**Comment by arlpetergadfort** [comment] 2022-08-11 17:30
@dineshannayya I think I see what the issue is here and have a PR opening soon.

**Comment by arlpetergadfort** [comment] 2022-08-11 17:33
https://github.com/The-OpenROAD-Project/OpenROAD/pull/2139

**Comment by arlpetergadfort** [comment] 2022-08-11 18:40
@dineshannayya this has been merged in so there should be honoring of the halo now

**Comment by donn** [comment] 2022-08-12 12:58
@arlpetergadfort OpenROAD updates are not automatically merged into OpenLane. I still need to pull it in.

**Comment by arlpetergadfort** [comment] 2022-08-12 13:04
> @arlpetergadfort OpenROAD updates are not automatically merged into OpenLane. I still need to pull it in.

@donn I don't use OpenLane, so it will be on you and the maintainers it to update OpenROAD for OpenLane

**Comment by dineshannayya** [comment] 2022-08-14 17:03
@arlpetergadfort My issue is resolved with locally building openlane docker built with your openroad  changes. Appreciate for quick follow-up.

**Comment by dineshannayya** [comment] 2022-08-15 07:08
@arlpetergadfort Even though Openlane flow is clean with latest PDN changes, I see uniformity of the Vertical power strip are missing.  This may create IR Drop issue ..

![pdn_stripe_issue](https://user-images.githubusercontent.com/8286294/184591312-b48312d6-a0f2-43e7-886f-4c925dae8ee9.png)

**Comment by arlpetergadfort** [comment] 2022-08-15 12:47
> @arlpetergadfort Even though Openlane flow is clean with latest PDN changes, I see uniformity of the Vertical power strip are missing. This may create IR Drop issue ..
> 
> ![pdn_stripe_issue](https://user-images.githubusercontent.com/8286294/184591312-b48312d6-a0f2-43e7-886f-4c925dae8ee9.png)

I guess the question is: does it cause IR drop issues? Please check the impact before raising the issue.
The reason they are missing is PDNgen removed them since they were only connected to 1 or fewer straps/pins, therefore they do not add to the grid in any meaningful way.

**Comment by donn** [comment] 2022-08-15 14:57
> @donn I don't use OpenLane, so it will be on you and the maintainers it to update OpenROAD for OpenLane

Then please refrain from proclaiming that something has been "merged in" in OpenLane issues. It may confuse users.

**Comment by arlpetergadfort** [comment] 2022-08-15 15:13
@donn I will, I clearly meant that it was integrated into OR and @dineshannayya (clearly understood).

**Closed** 2022-08-16 14:47 UTC
Labels: bug, OpenROAD
