### ISSUE TITLE
Post Simulation error in output reg

### ISSUE THREAD

**Issue by Khalique13** [The-OpenROAD-Project/OpenLane#552] opened 2021-08-19 12:34 UTC
### Environment
* Operating System Information: `Ubuntu -20.4`
* Docker Version: `docker --version`
    * If you're using Podman, please also include this information.
* OpenLane Tag in use: `Gate level Synthesis ` in the main OpenLane directory.

### Reproduction Material
* Upload a tarball containing the relevant design.
* List the commands used to run the design.

### Logs
```
Pre-lay-out simulation and post-layout simulation are not matching 
``` 
![image](https://user-images.githubusercontent.com/80625515/130069083-26affbc6-0e1a-416d-879e-4e5fccc0cb13.jpeg)

**Comment by Manarabdelaty** [comment] 2021-08-19 12:59
@Khalique13 Check https://github.com/The-OpenROAD-Project/OpenLane/issues/518. You need to pass `-DFUNCTIONAL -DUNIT_DELAY=#1` to iverilog. Also, if you are simulating the netlist with power pins, you need to make sure that you are connecting `VPWR` and `VGND` pins of the top level netlist to `1'b1` and `1'b0` respectively in the testbench. Also, you will need to pass `-DUSE_POWER_PINS` to iverilog to use the powered cell views.

**Comment by donn** [comment] 2021-08-20 09:37
Duplicate of #518, locked.

**Closed by donn** 2021-08-20 09:37 UTC

**Comment by Khalique13** [comment] 2021-08-20 09:49
Here I am getting syntax error in sky130_fd_sc_hd.v at line 5363

**Comment by donn** [comment] 2021-08-20 10:32
Please continue the discussion in #518, Khalique.
