### ISSUE TITLE
Diode Insertion fails

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenLane#1382] opened 2022-09-21 05:37 UTC
## Description
With `DIODE_INSERTION_STRATEGY=4` OpenLane flow fails.

## Expected behavior
Flow should work all diode insertion strategy.

## Environment

```
Kernel: Linux v3.10.0-1160.49.1.el7.x86_64
Distribution: centos 7
Python: v3.6.8 (OK)
Container Engine: docker v20.10.16 (OK)
OpenLane Git Version: 87173889682b67c490c96ded79b93aa2bb570a48
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

8717388 2022-09-20T00:03:58+02:00 Point to `open_pdks` upstream (#1372) - Kareem Farid -  (HEAD -> master, tag: 2022.09.20, origin/master, origin/HEAD)
3ee8cf0 2022-09-19T20:38:28+02:00 Use OpenDB as the Primary Layout Format (#1244) - Mohamed Gaber -  ()
d375db9 2022-09-15T13:35:19+02:00 [BOT] Update magic (#1318) - Openlane Bot -  (tag: 2022.09.16)
---
Git Remotes

origin	https://github.com/The-OpenROAD-Project/OpenLane.git (fetch)
origin	https://github.com/The-OpenROAD-Project/OpenLane.git (push)

```

## Reproduction Material

```
Update `design/spm/config.json` with `"DIODE_INSERTION_STRATEGY": 4,`
cd OpenLane
make mount
./flow.tcl -design spm
```
Flow fail with below log during diode insertion.

## Logs

```
[STEP 16]
[INFO]: Running Diode Insertion (log: designs/spm/runs/diode_4/logs/routing/16-diodes.log)...
[ERROR]: during executing: "openroad -python /openlane/scripts/odbpy/diodes.py place --diode-cell sky130_fd_sc_hd__diode_2 --diode-pin DIODE --fake-diode-cell sky130_fd_sc_hd__diode_2 --input-lef /openlane/designs/spm/runs/diode_4/tmp/merged.nom.lef --output-def /openlane/designs/spm/runs/diode_4/tmp/routing/16-diodes.def --output /openlane/designs/spm/runs/diode_4/tmp/routing/16-diodes.odb /openlane/designs/spm/runs/diode_4/tmp/14-spm.buffers_removed.odb |& tee /dev/null /openlane/designs/spm/runs/diode_4/logs/routing/16-diodes.log"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
OpenROAD 4174c3ad802d2ac1d04d387d2c4b883903f6647e 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
Usage: diodes.py [OPTIONS] COMMAND [ARGS]...
Try 'diodes.py --help' for help.

Error: No such command 'place'.
child process exited abnormally

[INFO]: Saving current set of views in 'designs/spm/runs/diode_4/results/final'...
[INFO]: Generating final set of reports...
[INFO]: Created manufacturability report at 'designs/spm/runs/diode_4/reports/manufacturability.rpt'.
[INFO]: Created metrics report at 'designs/spm/runs/diode_4/reports/metrics.csv'.
[INFO]: Saving runtime environment...
[ERROR]: Flow failed.

```

**Comment by maliberty** [comment] 2022-09-21 05:43
Duplicate of https://github.com/The-OpenROAD-Project/OpenLane/issues/1379 - proposed fix in https://github.com/The-OpenROAD-Project/OpenLane/pull/1381

**Closed by maliberty** 2022-09-21 05:43 UTC
