### ISSUE TITLE
DRC error when running user_project_wrapper

### ISSUE THREAD

**Issue by BYCakar** [The-OpenROAD-Project/OpenLane#1040] opened 2022-04-11 10:51 UTC
### Description
Hello everyone, I am trying to implement SRAM macros inside caravel user area. Everything works fine until DRC step. In the DRC step, I get this error message.
```
[ERROR]: during executing: "magic -noconsole -dnull -rcfile /home/burak/openmpw4_tools/pdk/sky130A/libs.tech/magic/sky130A.magicrc /openlane/scripts/magic/drc.tcl </dev/null |& tee >&@stdout /home/burak/openmpw4_tools/caravel_user_project/openlane/user_project_wrapper/runs/user_project_wrapper/logs/finishing/31-drc.log"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
child killed: kill signal

[ERROR]: Flow failed.
```
When I look at the 31-drc.log, I see these error messages.
```
...
Reading "sky130_fd_bd_sram__openram_dp_cell_cap_row".
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_cap_row" (byte position 2620068): Unknown layer/datatype in boundary, layer=33 type=42
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_cap_row" (byte position 2620772): Unknown layer/datatype in boundary, layer=33 type=43
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_cap_row" (byte position 2621732): Unknown layer/datatype in boundary, layer=22 type=21
...
Reading "sky130_fd_bd_sram__openram_dp_cell_dummy".
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_dummy" (byte position 3113978): Unknown layer/datatype in boundary, layer=33 type=42
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_dummy" (byte position 3117754): Unknown layer/datatype in boundary, layer=33 type=43
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_dummy" (byte position 3121946): Unknown layer/datatype in boundary, layer=22 type=21
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_dummy" (byte position 3126746): Unknown layer/datatype in boundary, layer=22 type=22
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_dummy" (byte position 3128794): Unknown layer/datatype in boundary, layer=235 type=0
...
Reading "sky130_fd_bd_sram__openram_dp_cell_replica".
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_replica" (byte position 3308236): Unknown layer/datatype in boundary, layer=33 type=42
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_replica" (byte position 3312012): Unknown layer/datatype in boundary, layer=33 type=43
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_replica" (byte position 3316204): Unknown layer/datatype in boundary, layer=22 type=21
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_replica" (byte position 3322668): Unknown layer/datatype in boundary, layer=22 type=22
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell_replica" (byte position 3324844): Unknown layer/datatype in boundary, layer=235 type=0
...
Reading "sky130_fd_bd_sram__openram_dp_cell".
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell" (byte position 3565294): Unknown layer/datatype in boundary, layer=33 type=42
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell" (byte position 3569070): Unknown layer/datatype in boundary, layer=33 type=43
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell" (byte position 3573262): Unknown layer/datatype in boundary, layer=22 type=21
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell" (byte position 3579726): Unknown layer/datatype in boundary, layer=22 type=22
Error while reading cell "sky130_fd_bd_sram__openram_dp_cell" (byte position 3581902): Unknown layer/datatype in boundary, layer=235 type=0
```
I added the relevant log file in reproducibles_and_logs.tar.gz .
### Environment
```
Kernel: Linux v5.13.0-39-generic
Distribution: ubuntu 20.04
Python: v3.8.10 (OK)
Container Engine: docker v20.10.7 (OK)
OpenLane Git Version: -dev
pip:click: INSTALLED
pip:pyyaml: INSTALLED
pip:venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

e4bfdd7 2022-02-22T16:59:14-03:00 Remove pip install, no longer needed (#953) - Vitor Bandeira -  (grafted, HEAD, tag: 2022.02.23_02.50.41)
```
### Expected behavior
No DRC errors expected.
### Reproduction Material and Logs
```
[reproducibles_and_logs.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/8463395/reproducibles_and_logs.tar.gz)
```

**Comment by vijayank88** [comment] 2022-04-11 11:04
@BYCakar 

Are you using mpw-5c tag?

**Comment by BYCakar** [comment] 2022-04-11 11:20
I think I am not using a tag, but a later version anyway. Git log is below.
```
commit afbb1601246c336b1c1e6cd87ecd85d9be8aa4d5 (HEAD, origin/main, origin/HEAD)
Merge: c2246f4 17c43a6
Author: Jeff DiCorpo <42048757+jeffdi@users.noreply.github.com>
Date:   Fri Mar 4 08:50:28 2022 -0800

    Merge pull request #92 from efabless/marwaneltoukhy-patch-1
    
    Add target to make run simulation on all testbenches

commit c2246f4feea7ef009274a759820e65d3e586dd0a
Merge: 8686b12 0eb93ef
Author: Jeff DiCorpo <42048757+jeffdi@users.noreply.github.com>
Date:   Fri Mar 4 08:49:43 2022 -0800

    Merge pull request #89 from efabless/kareefardi-patch-1
    
    fix make <block> running all make blocks

commit 8686b12dba856d224c486c3159108d45ab57a55c
Merge: 8b91e45 7566d6d
Author: Jeff DiCorpo <42048757+jeffdi@users.noreply.github.com>
Date:   Fri Mar 4 08:44:32 2022 -0800
```

**Comment by vijayank88** [comment] 2022-04-11 11:25
@BYCakar 
Please update as https://github.com/efabless/caravel_user_project/blob/main/docs/source/quickstart.rst with mpw-6a tag and re-run the flow and let us know.

**Comment by d-m-bailey** [comment] 2022-04-11 11:35
@BYCakar This may be an out of memory error. Try watching the memory usage before the crash.

**Comment by kareefardi** [comment] 2024-07-17 09:21
Closing this, Since it would be hard to reproduce this now. Please open a new issue if needed. Child killed is usually a sign of out of memory crash.

**Closed by kareefardi** 2024-07-17 09:21 UTC
Labels: MPW

**Comment by mguthaus** [comment] 2024-07-19 13:12
Those errors are expected. There were layers that are used in the macros that are not in the magic DRC deck for OPC etc.

**Comment by mguthaus** [comment] 2024-07-19 13:12
But we also cannot remove those layers. They are needed for manufacturing.
