### ISSUE TITLE
Post synthesis iverilog simulation gives error

### ISSUE THREAD

**Issue by manjunathrv** [The-OpenROAD-Project/OpenLane#527] opened 2021-08-06 06:32 UTC
**Describe the bug**
iVerilog simulation for the same test bench gives an error for post-synthesis gate-level netlist. 
The synthesis in Openlane is successful. 
Presynthesis test bench simulation is successful. 

**Expected behavior** </br>
Below Pre-synthesis iverliog output </br>
![image](https://user-images.githubusercontent.com/52245531/128459369-055c9622-966b-4f87-a0fd-9350d66a6919.png)

**Observed errors**</br>
iverilog simulation for Post synthesis 
![image](https://user-images.githubusercontent.com/52245531/128459689-046f3cec-ade3-455d-b33b-972be53ca450.png)

Also tried with adding unit delay commands in iverilog from issue https://github.com/The-OpenROAD-Project/OpenLane/issues/518
![image](https://user-images.githubusercontent.com/52245531/128463496-6630eb48-f929-42e7-b3ad-144a7f96a564.png)

run_synthesis was successful 
![image](https://user-images.githubusercontent.com/52245531/128464706-a2158301-40c2-432e-bc2c-e9830d44a52c.png)

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Openlane Version [ 2021.07.31_04.42.28] obtained from get_tag.py
 - open_pdks Version: [latest installed 31st July]
 - skywater-pdk Version: [latest installed 31st July]

**Comment by armleo** [comment] 2021-08-06 08:16
can you provide 5235 +- 10 lines of fs_sc_hd,v?
If it's defined as `wire 1;` then comment it out.

**Comment by manjunathrv** [comment] 2021-08-06 09:48
Thanks for the reply. Yes, it was wire 1; I have commented it. </br>
![image](https://user-images.githubusercontent.com/52245531/128492091-b567e025-87e3-4221-be1c-2562ce18e906.png)

iverilog simulation doesn't give errors. But the output as checked in gtkwave shows XXX. </br>

![image](https://user-images.githubusercontent.com/52245531/128492273-28e30927-4330-45b9-90ff-d1a79ed4a423.png)

**Comment by donn** [comment] 2021-08-06 11:19
Duplicate of #518

**Closed by donn** 2021-08-06 11:19 UTC
