### ISSUE TITLE
sky130hs fails on diode error

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenLane#906] opened 2022-02-07 19:45 UTC
### Description
If I run gcd with sky130hs (using #905 ) I get:

```
[WARNING STA-0328] port 'DIODE' not found.
[ERROR GRT-0069] Diode not found.
Error: groute.tcl, 74 GRT-0069

```
### Environment
Head of master

### Reproduction Material
In description / GH

### Expected behavior
No error

**Comment by tdene** [comment] 2022-02-07 19:46
I believe this is caused by [https://github.com/google/skywater-pdk/issues/358](https://github.com/google/skywater-pdk/issues/358)

**Comment by kareefardi** [comment] 2023-09-10 11:07
For some reason this no longer happens. Double checking if I missed something.

**Comment by kareefardi** [comment] 2023-09-12 19:46
This is probably handled at OpenROAD's end since the mentioned issue in this thread was not fixed. Closing this if similar issues appear please open a new issue.

**Closed by kareefardi** 2023-09-12 19:46 UTC
Labels: bug, Skywater PDK, blocked
