### ISSUE TITLE
Padframe generation

### ISSUE THREAD

**Issue by Syndace** [The-OpenROAD-Project/OpenLane#1314] opened 2022-09-05 12:01 UTC
I could use some help wrapping my head around the padframe generation procedure. As you are already aware (#1082), the documentation is outdated. Even after tracking down the 404s in the docs to https://github.com/efabless/caravel/tree/main/openlane/chip_io, I'm met with 10 months old scripts that don't work any more.

I found three potentially relevant scripts/commands:

- `scripts/odbpy/padringer.py`
- `scripts/padframe_generator.py`
- The `padframe_gen` interactive command, which uses `scripts/padframe_generator.py` under the hood (most promising to me but can't get it to work)

I'm a bit lost. None of the example designs shipped with OpenLane generate their own padframe either. How do I approach padframe generation?

**Comment by donn** [comment] 2022-09-05 12:42
It's been in this state from the day I started maintaining this codebase- I can't wrap my head around it, personally. I would be surprised if it still works.

Let me take a look.

**Comment by maliberty** [comment] 2022-09-06 03:31
OR provides pad frame generation as well if that is helpful (https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/pad/doc/README.md)

**Comment by Syndace** [comment] 2022-09-08 13:20
Thanks @maliberty, that was a great hint. I managed to add OR padframe generation to OpenLane's floorplanning script and it works quite well. The only thing I'm struggling with is connecting the padframe to the core power net, but that's out-of-scope for this issue I believe.

Feel free to close this issue if you don't want to keep it open for feature tracking purposes.

**Comment by maliberty** [comment] 2022-09-08 13:23
@donn do you want a contribution in this area or should I close this?

Feel free to open another issue for the pdn if needed.

**Comment by donn** [comment] 2022-09-08 14:06
No, I would appreciate a contribution in this area.

**Comment by Syndace** [comment] 2022-09-08 19:02
I'd be happy to contribute this once we've made it through the tapeout :)

**Comment by donn** [comment] 2024-09-12 12:16
You can track our progress adding this to OpenLane 2. (The problem is as a company literally selling a padframe there's not much of a drive for us to add one 😅)

https://github.com/efabless/openlane2/issues/508

**Closed as not planned by donn** 2024-09-12 12:16 UTC
Labels: enhancement, LibreLane

**Comment by riyasls** [comment] 2026-04-21 06:41
I’m currently working with OpenLane and trying to generate a padframe using the `padringer.py` script. I’ve attempted several approaches, but I’m running into issues and haven’t been able to get it working correctly. I would appreciate your help in resolving this and understanding the correct workflow.
